name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  file_picker: ^6.1.1
  firebase_storage: ^12.4.7
  path: ^1.9.0
  http: ^0.13.6
  video_player_web: ^2.3.5
  video_player: ^2.7.2
  cloud_firestore: ^5.0.0
  lottie: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/

