// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyymbM2NtigIMVpYP20goUeCwukYBarh8',
    appId: '1:379600488574:web:576a64654922c6cdebb02f',
    messagingSenderId: '379600488574',
    projectId: 'batsman-pro-2e8bc',
    authDomain: 'batsman-pro-2e8bc.firebaseapp.com',
    storageBucket: 'batsman-pro-2e8bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrcx3oABCnFAnilg1xhouxD6pZDgnGIdc',
    appId: '1:379600488574:android:d3efae3859d1d473ebb02f',
    messagingSenderId: '379600488574',
    projectId: 'batsman-pro-2e8bc',
    storageBucket: 'batsman-pro-2e8bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCajacQoyZjUiu8PMggL59VvA6LyyX9XZQ',
    appId: '1:379600488574:ios:533514c65025ca73ebb02f',
    messagingSenderId: '379600488574',
    projectId: 'batsman-pro-2e8bc',
    storageBucket: 'batsman-pro-2e8bc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCajacQoyZjUiu8PMggL59VvA6LyyX9XZQ',
    appId: '1:379600488574:ios:533514c65025ca73ebb02f',
    messagingSenderId: '379600488574',
    projectId: 'batsman-pro-2e8bc',
    storageBucket: 'batsman-pro-2e8bc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyymbM2NtigIMVpYP20goUeCwukYBarh8',
    appId: '1:379600488574:web:05c504bd002197f2ebb02f',
    messagingSenderId: '379600488574',
    projectId: 'batsman-pro-2e8bc',
    authDomain: 'batsman-pro-2e8bc.firebaseapp.com',
    storageBucket: 'batsman-pro-2e8bc.firebasestorage.app',
  );
}
